#ifndef PLAYER_DEFINES
#define PLAYER_DEFINES

#include "Graphic_Defines.h"

//****Link Moving-Animation defines****//

//Sonstiges
#define LINK_UPDATE_RADIUS 128

//Moving Tiles
//No Shield
#define LINK_MOVE_ANI_LEFT sf::IntRect(37*TILESIZE,5*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT sf::IntRect(36*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN sf::IntRect(34*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP sf::IntRect(38*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)

#define LINK_MOVE_ANI_LEFT_2 sf::IntRect(38*TILESIZE,5*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT_2 sf::IntRect(37*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN_2 sf::IntRect(35*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP_2 sf::IntRect(39*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)
//Shield 1
#define LINK_MOVE_ANI_LEFT_SHIELD_1 sf::IntRect(3*TILESIZE,0*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT_SHIELD_1 sf::IntRect(2*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN_SHIELD_1 sf::IntRect(0*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP_SHIELD_1 sf::IntRect(4*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)

#define LINK_MOVE_ANI_LEFT_2_SHIELD_1 sf::IntRect(4*TILESIZE,0*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT_2_SHIELD_1 sf::IntRect(3*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN_2_SHIELD_1 sf::IntRect(1*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP_2_SHIELD_1 sf::IntRect(5*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
//Shield 2
#define LINK_MOVE_ANI_LEFT_SHIELD_2 sf::IntRect(2*TILESIZE,3*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT_SHIELD_2 sf::IntRect(1*TILESIZE,3*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN_SHIELD_2 sf::IntRect(0*TILESIZE,2*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP_SHIELD_2 sf::IntRect(0*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)

#define LINK_MOVE_ANI_LEFT_2_SHIELD_2 sf::IntRect(3*TILESIZE,3*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT_2_SHIELD_2 sf::IntRect(2*TILESIZE,3*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN_2_SHIELD_2 sf::IntRect(0*TILESIZE,4*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP_2_SHIELD_2 sf::IntRect(1*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)
//Shield 3
#define LINK_MOVE_ANI_LEFT_SHIELD_3 sf::IntRect(3*TILESIZE,2*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT_SHIELD_3 sf::IntRect(2*TILESIZE,2*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN_SHIELD_3 sf::IntRect(4*TILESIZE,3*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP_SHIELD_3 sf::IntRect(3*TILESIZE,2*TILESIZE,TILESIZE,TILESIZE)

#define LINK_MOVE_ANI_LEFT_2_SHIELD_3 sf::IntRect(2*TILESIZE,2*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_RIGHT_2_SHIELD_3 sf::IntRect(1*TILESIZE,2*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_DOWN_2_SHIELD_3 sf::IntRect(3*TILESIZE,3*TILESIZE,TILESIZE,TILESIZE)
#define LINK_MOVE_ANI_UP_2_SHIELD_3 sf::IntRect(3*TILESIZE,4*TILESIZE,TILESIZE,TILESIZE)

//Swimming Tiles
#define LINK_SWIMM_ANI_LEFT sf::IntRect(10*TILESIZE,0*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_SWIMM_ANI_RIGHT sf::IntRect(9*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_SWIMM_ANI_DOWN sf::IntRect(7*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_SWIMM_ANI_UP sf::IntRect(11*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)

#define LINK_SWIMM_ANI_LEFT_2 sf::IntRect(11*TILESIZE,0*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_SWIMM_ANI_RIGHT_2 sf::IntRect(10*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_SWIMM_ANI_DOWN_2 sf::IntRect(8*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_SWIMM_ANI_UP_2 sf::IntRect(12*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)

//Fighting Tiles (Sword)
#define LINK_FIGHT_ANI_LEFT sf::IntRect(7*TILESIZE,0*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_FIGHT_ANI_RIGHT sf::IntRect(6*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FIGHT_ANI_DOWN sf::IntRect(0*TILESIZE,1*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FIGHT_ANI_UP sf::IntRect(1*TILESIZE,1*TILESIZE,TILESIZE,TILESIZE)

//Found Tile
#define LINK_FIND_ONE_HAND sf::IntRect(2*TILESIZE,1*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FIND_TWO_HANDS sf::IntRect(3*TILESIZE,1*TILESIZE,TILESIZE,TILESIZE)

#define LINK_FIND_ONE_HAND_SWIMM sf::IntRect(14*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FIND_TWO_HANDS_SWIMM sf::IntRect(13*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)

//Hammer Tile
#define LINK_HAMMER_LEFT sf::IntRect(22*TILESIZE,14*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_HAMMER_RIGHT sf::IntRect(21*TILESIZE,14*TILESIZE,TILESIZE,TILESIZE)
#define LINK_HAMMER_DOWN sf::IntRect(21*TILESIZE,13*TILESIZE,TILESIZE,TILESIZE)
#define LINK_HAMMER_UP sf::IntRect(21*TILESIZE,15*TILESIZE,TILESIZE,TILESIZE)

#define LINK_HAMMER_LEFT_2 sf::IntRect(21*TILESIZE,5*TILESIZE,-TILESIZE,TILESIZE)
#define LINK_HAMMER_RIGHT_2 sf::IntRect(20*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)
#define LINK_HAMMER_DOWN_2 sf::IntRect(23*TILESIZE,4*TILESIZE,TILESIZE,TILESIZE)
#define LINK_HAMMER_UP_2 sf::IntRect(22*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)

//Die
#define LINK_DIE sf::IntRect(40*TILESIZE,5*TILESIZE,TILESIZE,TILESIZE)

//Fall Tile
#define LINK_FALL_1 sf::IntRect(47*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FALL_2 sf::IntRect(48*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FALL_3 sf::IntRect(49*TILESIZE,0*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FALL_4 sf::IntRect(49*TILESIZE,1*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FALL_5 sf::IntRect(49*TILESIZE,2*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FALL_6 sf::IntRect(48*TILESIZE,2*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FALL_7 sf::IntRect(47*TILESIZE,2*TILESIZE,TILESIZE,TILESIZE)
#define LINK_FALL_8 sf::IntRect(47*TILESIZE,1*TILESIZE,TILESIZE,TILESIZE)

//**Moving Events defines**//
#define LEFT 0
#define RIGHT 1
#define DOWN 2
#define UP 3

//Color Codes
#define RED_ARMOR sf::Color(192,0,0)
#define GREEN_ARMOR sf::Color(0,192,0)
#define BLUE_ARMOR sf::Color(0,0,192)
#define YELLOW_ARMOR sf::Color(192,192,0)

#endif