#ifndef WINDOW_DEFINES
#define WINDOW_DEFINES

#include "Graphic_Defines.h"

#define WINDOW_SIZE_X (19*ZOOMSIZE)
#define WINDOW_SIZE_Y (19*ZOOMSIZE)

#define INVENTORY_SCREEN_SIZE_X (WINDOW_SIZE_X-40)
#define INVENTORY_SCREEN_SIZE_Y (WINDOW_SIZE_Y-100)
#define INVENTORY_SCREEN_POSITION_X 20
#define INVENTORY_SCREEN_POSITION_Y 80

#endif